apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      # 1. Add this for private registry access
      imagePullSecrets:
      - name: ghcr-login-secret 
      
      containers:
      - name: secure-app
        # 2. Point to the Registry, not the local file
        image: ghcr.io/ratchmartins/cop-450/secure-app:latest
        
        # 3. Change to 'Always' so K8s fetches the newest code
        imagePullPolicy: Always 
        
        env:
        - name: FLASK_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5000
